<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  

<xacro:macro name="plate" params="parent name *origin length width height plate_thickness color">
    <joint name="${parent}_${name}_base_joint" type="fixed">
        <xacro:insert_block name="origin"/>
        <parent link="${parent}"/>
        <child link="${name}_plate_link"/>
    </joint>
    <link name="${name}_plate_link">
        <visual>
            <!-- <origin xyz="${-0.5 * length} ${-0.5 * width} ${-1/2 * plate_thickness}"/> -->
            <origin xyz="0 0 ${-0.5 * plate_thickness}"/>
            <geometry>
                <box size="${length} ${width} ${plate_thickness}"/>
      </geometry>
      <material name="${color}"/>
    </visual>
        <collision>
            <!-- <origin xyz="${1/2 * length} ${-1/2 * width} ${-1/2 * plate_thickness}"/> -->
            <origin xyz="0 0 ${-0.5 * plate_thickness}"/>
            <geometry>
                <box size="${length} ${width} ${plate_thickness}"/>
            </geometry>
        </collision>
    </link>
    
</xacro:macro>
</robot>
